### ISSUE TITLE
exampleSite doesn't work out of the box with latest Hugo

### ISSUE THREAD

**Issue by iouwon** [geschke/hugo-tikva#5]
Using hugo 0.69.0 on ubuntu and cloning the latest

Running the sample site it fails to build with the error:

**...content/sections/footer/column01.md:1:1": plain HTML documents not supported**

However adding frontmatter tags to the beginning of the file in the error msg fixes, so the content of the file looks like:

+++
+++
&lt;div&gt;
This is a placeholder for a content file of the footer. You can use Markdown or HTML here. Just place your content files into a folder "sections/footer" in your content directory, make the page bundle "headless" and enable the footer in the site config file.
&lt;/div&gt;

**Comment by geschke** [comment]
Yeah, we love BC breaks... I will check this at soon as possible, but please be patient. Thanks for your feedback!

**Comment by geschke** [comment]
Fixed in 85fa1db8 

Thanks for reporting!
